# This Makefile automatically generated by configure.
.POSIX:

CC =		cc
CFLAGS =	-ggdb -O2 -DREGEX -w -Ibsd -Wall
PREFIX =	/usr/local
MANDIR =	/usr/local/man

PROG =	mg
OBJS =	autoexec.o basic.o bell.o buffer.o cinfo.o dir.o display.o \
	echo.o extend.o file.o fileio.o funmap.o help.o kbd.o keymap.o \
	line.o macro.o main.o match.o modes.o paragraph.o re_search.o \
	region.o search.o spawn.o tty.o ttyio.o ttykbd.o undo.o util.o \
	version.o window.o word.o yank.o cmode.o cscope.o dired.o \
	grep.o tags.o fparseln.o fstatat.o futimens.o getline.o \
	reallocarray.o strlcat.o strlcpy.o strndup.o strtonum.o \
	interpreter.o extensions.o kdg.o

all: ${PROG}

${PROG}: ${OBJS}
	${CC} ${LDFLAGS} -o ${PROG} ${OBJS} -lncursesw

install:
	install -d ${DESTDIR}${PREFIX}/bin
	install -d ${DESTDIR}${MANDIR}/man1
	install -c -s -m 755 ${PROG} ${DESTDIR}${PREFIX}/bin
	install -c -m 644 mg.1 ${DESTDIR}${MANDIR}/man1/${PROG}.1

test:
	echo "No tests"

clean:
	rm -f ${PROG} ${OBJS}

distclean: clean
	rm -f Makefile config.h *.bak
